name: hr-cnn            # default is root
channels:
- defaults
dependencies:         # everything under this, installed by conda
- python=2.7
- docopt=0.6.2
- scipy=1.1.0
- h5py=2.8.0
- opencv=3.4.2
- boost=1.65.1
- bob.blitz=2.0.16
- pytorch=0.4.0
- torchvision=0.2.1
- pillow=6.0.0
- python-lmdb=0.94